// StoryGuideLayoutGenerated.ts
// Generated by test/render_story_ui.mjs. Edit web/story-ui-layout.mjs instead.

export type StoryGuideSlot = {
    x: number;
    y: number;
    width: number;
    height: number;
};

export type StoryGuideStep = {
    id: string;
    index: string;
    title: string;
    root: string;
    slot: StoryGuideSlot;
};

export const STORY_GUIDE_TEXTURE = {
    widthPx: 1500,
    heightPx: 1000,
    widthCm: 30,
    heightCm: 20,
    pixelsPerCm: 50,
};

export const STORY_GUIDE_PANEL = {
    width: 30,
    height: 20,
};

export const STORY_GUIDE_STEPS: StoryGuideStep[] = [
    {
        "id": "intro",
        "index": "01",
        "title": "Intro",
        "root": "C00_Intro_Field_Basics",
        "slot": {
            "x": -7,
            "y": 4.04,
            "width": 13.2,
            "height": 2.72
        }
    },
    {
        "id": "definition",
        "index": "02",
        "title": "Definition",
        "root": "C01_Math_Definition",
        "slot": {
            "x": 7,
            "y": 4.04,
            "width": 13.2,
            "height": 2.72
        }
    },
    {
        "id": "motion",
        "index": "03",
        "title": "Motion",
        "root": "C02_Motion_Field_Plane",
        "slot": {
            "x": -7,
            "y": 0.72,
            "width": 13.2,
            "height": 2.72
        }
    },
    {
        "id": "patterns",
        "index": "04",
        "title": "Patterns",
        "root": "C02_Transition_Field_Cubes",
        "slot": {
            "x": 7,
            "y": 0.72,
            "width": 13.2,
            "height": 2.72
        }
    },
    {
        "id": "metrics",
        "index": "05",
        "title": "Metrics",
        "root": "C02_Metrics_Probe",
        "slot": {
            "x": -7,
            "y": -2.6,
            "width": 13.2,
            "height": 2.72
        }
    },
    {
        "id": "examples",
        "index": "06",
        "title": "Three fields",
        "root": "C03_Three_Fields_Gravity_Magnetism_Wind",
        "slot": {
            "x": 7,
            "y": -2.6,
            "width": 13.2,
            "height": 2.72
        }
    }
];

export const STORY_GUIDE_NAV = {
    back: {"x":-11,"y":-7.44,"width":5.2,"height":2.24},
    next: {"x":11,"y":-7.44,"width":5.2,"height":2.24},
    progress: {"x":0,"y":-7.44,"width":14.4,"height":2.24},
};

export const STORY_GUIDE_UTILITY = {
    follow: {"x":7.06,"y":7.84,"width":3.8,"height":1.52},
    fold: {"x":11.46,"y":7.84,"width":3.8,"height":1.52},
};

export const STORY_GUIDE_UTILITY_FOLDED = {
    follow: {"x":7.3,"y":-8.3,"width":3.8,"height":1.52},
    fold: {"x":11.54,"y":-8.3,"width":3.8,"height":1.52},
};
