// StoryGuideLayoutGenerated.ts
// Generated by test/render_story_ui.mjs. Edit web/story-ui-layout.mjs instead.

export type StoryGuideSlot = {
    x: number;
    y: number;
    width: number;
    height: number;
};

export type StoryGuideStep = {
    id: string;
    index: string;
    title: string;
    root: string;
    slot: StoryGuideSlot;
};

export type StoryGuideExample = {
    id: string;
    index: string;
    title: string;
    slot: StoryGuideSlot;
};

export const STORY_GUIDE_TEXTURE = {
    widthPx: 1500,
    heightPx: 1000,
    widthCm: 30,
    heightCm: 20,
    pixelsPerCm: 50,
};

export const STORY_GUIDE_PANEL = {
    width: 30,
    height: 20,
};

export const STORY_GUIDE_STEPS: StoryGuideStep[] = [
    {
        "id": "intro",
        "index": "01",
        "title": "Intro",
        "root": "C00_Intro",
        "slot": {
            "x": -7,
            "y": 3.54,
            "width": 13.2,
            "height": 3.4
        }
    },
    {
        "id": "motion_fields",
        "index": "02",
        "title": "Motion Fields",
        "root": "C01_Motion_Fields",
        "slot": {
            "x": 7,
            "y": 3.54,
            "width": 13.2,
            "height": 3.4
        }
    },
    {
        "id": "theory",
        "index": "03",
        "title": "Theory",
        "root": "C02_Theory",
        "slot": {
            "x": -7,
            "y": -0.62,
            "width": 13.2,
            "height": 3.4
        }
    },
    {
        "id": "examples",
        "index": "04",
        "title": "Real World Examples",
        "root": "C03_Real_World_Examples",
        "slot": {
            "x": 7,
            "y": -0.62,
            "width": 13.2,
            "height": 3.4
        }
    }
];

export const STORY_GUIDE_EXAMPLES = {
    back: {"x":-11.2,"y":7.76,"width":4.8,"height":1.68},
    cards: [
    {
        "id": "gravity",
        "index": "01",
        "title": "Gravity",
        "slot": {
            "x": 0,
            "y": 3.7,
            "width": 27.2,
            "height": 3.08
        }
    },
    {
        "id": "magnetism",
        "index": "02",
        "title": "Magnetism",
        "slot": {
            "x": 0,
            "y": -0.14,
            "width": 27.2,
            "height": 3.08
        }
    },
    {
        "id": "wind",
        "index": "03",
        "title": "Wind",
        "slot": {
            "x": 0,
            "y": -3.98,
            "width": 27.2,
            "height": 3.08
        }
    }
] as StoryGuideExample[],
};

export const STORY_GUIDE_NAV = {
    back: {"x":-11,"y":-7.44,"width":5.2,"height":2.24},
    next: {"x":11,"y":-7.44,"width":5.2,"height":2.24},
    progress: {"x":0,"y":-7.44,"width":14.4,"height":2.24},
};

export const STORY_GUIDE_UTILITY = {
    follow: {"x":7.06,"y":7.84,"width":3.8,"height":1.52},
    fold: {"x":11.46,"y":7.84,"width":3.8,"height":1.52},
};
