// Bakes the web view's data files (gfs.bin / gfs.json / storms.json) into
// TypeScript modules the Lens Studio project can import directly. No runtime
// network access required — the snapshot is frozen at bake time.
//
//   GfsData.ts   exports one selected GFS timestep as quantized numeric arrays
//   StormsData.ts exports STORMS

import { readFile, writeFile } from "node:fs/promises";
import { Buffer } from "node:buffer";
import { normalizeStormPayload, renderStormsTs } from "./storm_data.mjs";

const ROOT = "/Users/armand/Documents/specs-samples/Vector-Fields";

// ----- GFS -----
const gfsMeta = JSON.parse(await readFile(`${ROOT}/web/public/gfs.json`, "utf8"));
const gfsBin = await readFile(`${ROOT}/web/public/gfs.bin`);
const allGfs = new Float32Array(gfsBin.buffer, gfsBin.byteOffset, gfsBin.byteLength / 4);
const cellsPerStep = gfsMeta.nx * gfsMeta.ny;
const totalPerVar = cellsPerStep * gfsMeta.nt;
const now = Date.now();
const ref = Date.parse(gfsMeta.refTime);
const stepMs = gfsMeta.stepHours * 3600 * 1000;
const envIdx = process.env.GFS_TIME_INDEX ? Number(process.env.GFS_TIME_INDEX) : NaN;
const selectedIdx = Number.isFinite(envIdx)
  ? Math.max(0, Math.min(gfsMeta.nt - 1, Math.round(envIdx)))
  : Math.max(0, Math.min(gfsMeta.nt - 1, Math.round((now - ref) / stepMs)));
const selectedTime = gfsMeta.times[selectedIdx];
const quantScale = 100;
const uStart = selectedIdx * cellsPerStep;
const vStart = totalPerVar + selectedIdx * cellsPerStep;

function quantizeSlice(start) {
  const out = new Array(cellsPerStep);
  for (let i = 0; i < cellsPerStep; i++) {
    const q = Math.round(allGfs[start + i] * quantScale);
    out[i] = Math.max(-32768, Math.min(32767, q));
  }
  return out;
}

function formatIntArray(values) {
  const lines = [];
  const perLine = 24;
  for (let i = 0; i < values.length; i += perLine) {
    lines.push("  " + values.slice(i, i + perLine).join(", "));
  }
  return "[\n" + lines.join(",\n") + "\n]";
}

const gfsLensMeta = {
  ...gfsMeta,
  refTime: selectedTime,
  endTime: selectedTime,
  nt: 1,
  times: [selectedTime],
  bakedFromWindow: {
    refTime: gfsMeta.refTime,
    endTime: gfsMeta.endTime,
    times: gfsMeta.times,
    selectedIndex: selectedIdx,
  },
  layout: "Int16 centi-m/s arrays baked for Lens Studio, [u, v] for one selected timestep",
};

const gfsTs = `// AUTO-GENERATED by test/bake_for_ls.mjs — do not edit by hand.
// Source: ${gfsMeta.source}
// Source window: ${gfsMeta.refTime} → ${gfsMeta.endTime} (${gfsMeta.nt} timesteps × ${gfsMeta.stepHours} h)
// Baked timestep: ${selectedTime}
// Grid:   ${gfsMeta.nx} lon × ${gfsMeta.ny} lat at ${gfsMeta.lonRes}° / ${gfsMeta.latRes}°

export const GFS_META = ${JSON.stringify(gfsLensMeta, null, 2)};

const GFS_QUANT_SCALE = ${quantScale};
const GFS_U_I16: number[] = ${formatIntArray(quantizeSlice(uStart))};
const GFS_V_I16: number[] = ${formatIntArray(quantizeSlice(vStart))};

let _cached: { u: Float32Array; v: Float32Array } | null = null;
export function loadGfsArrays(): { u: Float32Array; v: Float32Array } {
  if (_cached) return _cached;
  const total = GFS_META.nt * GFS_META.ny * GFS_META.nx;
  const u = new Float32Array(total);
  const v = new Float32Array(total);
  for (let i = 0; i < total; i++) {
    u[i] = GFS_U_I16[i] / GFS_QUANT_SCALE;
    v[i] = GFS_V_I16[i] / GFS_QUANT_SCALE;
  }
  _cached = { u, v };
  return _cached;
}
`;
await writeFile(`${ROOT}/Assets/Scripts/GfsData.ts`, gfsTs);
console.log(`wrote Assets/Scripts/GfsData.ts (${(gfsTs.length / 1024).toFixed(0)} KB, selected ${selectedTime})`);

// ----- Storms -----
const storms = normalizeStormPayload(JSON.parse(await readFile(`${ROOT}/web/public/storms.json`, "utf8")));
const stormsTs = renderStormsTs(storms);
await writeFile(`${ROOT}/Assets/Scripts/StormsData.ts`, stormsTs);
console.log(`wrote Assets/Scripts/StormsData.ts (${storms.storms.length} storms)`);
