import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import puppeteer from "puppeteer";
import { STORY_UI_LAYOUT } from "../web/story-ui-layout.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const htmlPath = path.join(root, "web", "story-ui-templates.html");
const browserLayoutPath = path.join(root, "web", "story-ui-layout.browser.js");
const outDir = path.join(root, "Assets", "Images", "StoryUI");
const layoutJsonPath = path.join(outDir, "story_ui_layout.json");
const layoutTsPath = path.join(root, "Assets", "Scripts", "StoryGuideLayoutGenerated.ts");

const captures = [
  ["#panel", "chapter_panel.png"],
  ...STORY_UI_LAYOUT.steps.map((step) => step.id).flatMap((id) => (
    ["normal", "active", "pressed"].map((state) => [`#card_${id}_${state}`, `card_${id}_${state}.png`])
  )),
  ["#nav_back_normal", "nav_back_normal.png"],
  ["#nav_back_pressed", "nav_back_pressed.png"],
  ["#nav_next_normal", "nav_next_normal.png"],
  ["#nav_next_pressed", "nav_next_pressed.png"],
  ["#utility_follow_on", "utility_follow_on.png"],
  ["#utility_follow_off", "utility_follow_off.png"],
  ["#utility_follow_pressed", "utility_follow_pressed.png"],
  ["#utility_fold_open", "utility_fold_open.png"],
  ["#utility_fold_closed", "utility_fold_closed.png"],
  ["#utility_fold_pressed", "utility_fold_pressed.png"],
];

await fs.mkdir(outDir, { recursive: true });
await fs.writeFile(browserLayoutPath, `window.STORY_UI_LAYOUT = ${JSON.stringify(STORY_UI_LAYOUT, null, 2)};\n`);

const browser = await puppeteer.launch({ headless: "new" });
const page = await browser.newPage();
await page.setViewport({ width: 1600, height: 1400, deviceScaleFactor: 1 });
await page.goto(pathToFileURL(htmlPath).href, { waitUntil: "domcontentloaded" });
await page.waitForFunction(() => window.storyUiReady === true);
await page.evaluateHandle("document.fonts.ready");

for (const [selector, filename] of captures) {
  const element = await page.$(selector);
  if (!element) throw new Error(`Missing capture target ${selector}`);
  await element.screenshot({
    path: path.join(outDir, filename),
    omitBackground: true,
  });
}

await browser.close();

await fs.writeFile(layoutJsonPath, JSON.stringify(STORY_UI_LAYOUT, null, 2) + "\n");
await fs.writeFile(layoutTsPath, buildLayoutTs(STORY_UI_LAYOUT));

console.log(`Rendered ${captures.length} story UI textures to ${path.relative(root, outDir)}`);
console.log(`Wrote ${path.relative(root, layoutJsonPath)}`);
console.log(`Wrote ${path.relative(root, layoutTsPath)}`);

function buildLayoutTs(spec) {
  const steps = spec.steps.map((step) => {
    const slot = spec.slots.find((s) => s.id === `card_${step.id}`);
    return {
      id: step.id,
      index: step.index,
      title: step.title,
      root: step.root,
      slot: slot.cm,
    };
  });
  const navBack = spec.slots.find((s) => s.id === "nav_back").cm;
  const navNext = spec.slots.find((s) => s.id === "nav_next").cm;
  const progress = spec.slots.find((s) => s.id === "progress").cm;
  const utilityFollow = spec.slots.find((s) => s.id === "utility_follow").cm;
  const utilityFold = spec.slots.find((s) => s.id === "utility_fold").cm;

  return `// StoryGuideLayoutGenerated.ts\n// Generated by test/render_story_ui.mjs. Edit web/story-ui-layout.mjs instead.\n\nexport type StoryGuideSlot = {\n    x: number;\n    y: number;\n    width: number;\n    height: number;\n};\n\nexport type StoryGuideStep = {\n    id: string;\n    index: string;\n    title: string;\n    root: string;\n    slot: StoryGuideSlot;\n};\n\nexport const STORY_GUIDE_TEXTURE = {\n    widthPx: ${spec.texture.widthPx},\n    heightPx: ${spec.texture.heightPx},\n    widthCm: ${spec.texture.widthCm},\n    heightCm: ${spec.texture.heightCm},\n    pixelsPerCm: ${spec.texture.pixelsPerCm},\n};\n\nexport const STORY_GUIDE_PANEL = {\n    width: ${spec.texture.widthCm},\n    height: ${spec.texture.heightCm},\n};\n\nexport const STORY_GUIDE_STEPS: StoryGuideStep[] = ${JSON.stringify(steps, null, 4)};\n\nexport const STORY_GUIDE_NAV = {\n    back: ${JSON.stringify(navBack)},\n    next: ${JSON.stringify(navNext)},\n    progress: ${JSON.stringify(progress)},\n};\n\nexport const STORY_GUIDE_UTILITY = {\n    follow: ${JSON.stringify(utilityFollow)},\n    fold: ${JSON.stringify(utilityFold)},\n};\n`;
}
